version: '3'

networks:
  webapp:

services:

  

  mysqldb:
    container_name: mysqldb
    image: mysql:8.1
    ports:
      - ":3306"
    environment:
        MYSQL_DATABASE: db_safexpress
        MYSQL_PASSWORD=: secret
        MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webapp

  phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - 9002:80
      environment:
        - PMA_ARBITRARY=1

volumes:
    db-data: ~
