version: '3'

networks:
  webapp:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
    - "80:80"
    links:
      - php
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - mysqldb
    networks:
      - webapp
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
       - .:/var/www
    ports:
      - "9001:9000"
    networks:
      - webapp

  mysqldb:
    container_name: mysqldb
    image: mysql:8.1
    ports:
      - 3306:3306
    environment:
        MYSQL_DATABASE: db_safexpress
        MYSQL_PASSWORD=: secret
        MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - webapp

  phpmyadmin:
      image: phpmyadmin:latest
      ports:
        - 9002:80
      environment:
        - PMA_ARBITRARY=1

volumes:
    db-data: ~
